name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        dotnet pack -c Release -p:PackageVersion=$VERSION
    - name: Push
      run: dotnet nuget push **\*.nupkg -s nuget.org -k ${{ secrets.NUGET_ORG_API_KEY }}
